version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: root
    group: root
    mode: 755
    type:
      - file