version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: root
    group: root
    mode: 755
    type:
      - file