version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/your_domain/
  - source: your_domain.conf
    destination: /etc/apache2/sites-available/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: root
    group: root
    mode: 755
    type:
      - file